/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package test.git;

/**
 *
 * @author Mashuk
 */
public class SCalender extends javax.swing.JFrame {

    /**
     * Creates new form SCalender
     */
    public SCalender() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scLeftPane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnJanuary = new javax.swing.JButton();
        btnFebruary = new javax.swing.JButton();
        btnMarch = new javax.swing.JButton();
        btnApril = new javax.swing.JButton();
        btnMay = new javax.swing.JButton();
        btnJune = new javax.swing.JButton();
        btnJuly = new javax.swing.JButton();
        btnAugust = new javax.swing.JButton();
        btnSeptember = new javax.swing.JButton();
        btnOctober = new javax.swing.JButton();
        btnNovember = new javax.swing.JButton();
        btnDecember = new javax.swing.JButton();
        lblSelectYear = new javax.swing.JLabel();
        cmbYear = new javax.swing.JComboBox();
        scMainPane = new javax.swing.JPanel();
        scCalenderPane = new javax.swing.JPanel();
        sCalenderCellOne = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sCalenderCellTwo = new javax.swing.JPanel();
        sCalenderCellThree = new javax.swing.JPanel();
        sCalenderCellFour = new javax.swing.JPanel();
        sCalenderCellFive = new javax.swing.JPanel();
        sCalenderCellSix = new javax.swing.JPanel();
        sCalenderCellSeven = new javax.swing.JPanel();
        sCalenderCellEight = new javax.swing.JPanel();
        sCalenderCellNine = new javax.swing.JPanel();
        sCalenderCellTen = new javax.swing.JPanel();
        sCalenderCellEleven = new javax.swing.JPanel();
        sCalenderCellTwelve = new javax.swing.JPanel();
        sCalenderCellThirteen = new javax.swing.JPanel();
        sCalenderCellFourteen = new javax.swing.JPanel();
        sCalenderCellFifteen = new javax.swing.JPanel();
        sCalenderCellSixteen = new javax.swing.JPanel();
        sCalenderCellSeventeen = new javax.swing.JPanel();
        sCalenderCellEighteen = new javax.swing.JPanel();
        sCalenderCellNineteen = new javax.swing.JPanel();
        sCalenderCellTwenty = new javax.swing.JPanel();
        sCalenderCellTwentyOne = new javax.swing.JPanel();
        sCalenderCellTwentyTwo = new javax.swing.JPanel();
        sCalenderCellTwentyThree = new javax.swing.JPanel();
        sCalenderCellTwentyFour = new javax.swing.JPanel();
        sCalenderCellTwentyFive = new javax.swing.JPanel();
        sCalenderCellTwentySix = new javax.swing.JPanel();
        sCalenderCellTwentySeven = new javax.swing.JPanel();
        sCalenderCellTwentyEight = new javax.swing.JPanel();
        sCalenderCellTwentyNine = new javax.swing.JPanel();
        sCalenderCellThirty = new javax.swing.JPanel();
        sCalenderCellThirtyOne = new javax.swing.JPanel();
        sCalenderCellThirtyTwo = new javax.swing.JPanel();
        sCalenderCellThirtyThree = new javax.swing.JPanel();
        sCalenderCellThirtyFour = new javax.swing.JPanel();
        sCalenderCellThirtyFive = new javax.swing.JPanel();
        sCalenderCellThirtySix = new javax.swing.JPanel();
        sCalenderCellThirtySeven = new javax.swing.JPanel();
        sCalenderCellThirtyEight = new javax.swing.JPanel();
        sCalenderCellThirtyNine = new javax.swing.JPanel();
        sCalenderCellFourty = new javax.swing.JPanel();
        sCalenderCellFourtyOne = new javax.swing.JPanel();
        sCalenderCellFourtyTwo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(4, 3));

        btnJanuary.setText("January");
        btnJanuary.setFocusPainted(false);
        btnJanuary.setFocusable(false);
        jPanel1.add(btnJanuary);

        btnFebruary.setText("February");
        btnFebruary.setFocusPainted(false);
        btnFebruary.setFocusable(false);
        jPanel1.add(btnFebruary);

        btnMarch.setText("March");
        btnMarch.setFocusPainted(false);
        btnMarch.setFocusable(false);
        jPanel1.add(btnMarch);

        btnApril.setText("April");
        btnApril.setFocusPainted(false);
        btnApril.setFocusable(false);
        jPanel1.add(btnApril);

        btnMay.setText("May");
        btnMay.setFocusPainted(false);
        btnMay.setFocusable(false);
        jPanel1.add(btnMay);

        btnJune.setText("June");
        btnJune.setFocusPainted(false);
        btnJune.setFocusable(false);
        jPanel1.add(btnJune);

        btnJuly.setText("July");
        btnJuly.setFocusPainted(false);
        btnJuly.setFocusable(false);
        jPanel1.add(btnJuly);

        btnAugust.setText("August");
        btnAugust.setFocusPainted(false);
        btnAugust.setFocusable(false);
        jPanel1.add(btnAugust);

        btnSeptember.setText("September");
        btnSeptember.setFocusPainted(false);
        btnSeptember.setFocusable(false);
        jPanel1.add(btnSeptember);

        btnOctober.setText("October");
        btnOctober.setFocusPainted(false);
        btnOctober.setFocusable(false);
        jPanel1.add(btnOctober);

        btnNovember.setText("November");
        btnNovember.setFocusPainted(false);
        btnNovember.setFocusable(false);
        jPanel1.add(btnNovember);

        btnDecember.setText("December");
        btnDecember.setFocusPainted(false);
        btnDecember.setFocusable(false);
        jPanel1.add(btnDecember);

        lblSelectYear.setText("Select Year:");

        cmbYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout scLeftPaneLayout = new javax.swing.GroupLayout(scLeftPane);
        scLeftPane.setLayout(scLeftPaneLayout);
        scLeftPaneLayout.setHorizontalGroup(
            scLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scLeftPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(scLeftPaneLayout.createSequentialGroup()
                        .addComponent(lblSelectYear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        scLeftPaneLayout.setVerticalGroup(
            scLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scLeftPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(scLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectYear)
                    .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(338, Short.MAX_VALUE))
        );

        getContentPane().add(scLeftPane, java.awt.BorderLayout.LINE_START);

        scMainPane.setLayout(new java.awt.BorderLayout());

        scCalenderPane.setLayout(new java.awt.GridLayout(6, 7));

        sCalenderCellOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellOne.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setText("1");
        sCalenderCellOne.add(jLabel1);

        scCalenderPane.add(sCalenderCellOne);

        sCalenderCellTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellTwo.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellTwo);

        sCalenderCellThree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellThree.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellThree);

        sCalenderCellFour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellFour.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellFour);

        sCalenderCellFive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellFive.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellFive);

        sCalenderCellSix.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellSix.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellSix);

        sCalenderCellSeven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellSeven.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellSeven);

        sCalenderCellEight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellEight.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellEight);

        sCalenderCellNine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellNine.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellNine);

        sCalenderCellTen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellTen.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellTen);

        sCalenderCellEleven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellEleven.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellEleven);

        sCalenderCellTwelve.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellTwelve.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellTwelve);

        sCalenderCellThirteen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellThirteen.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellThirteen);

        sCalenderCellFourteen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellFourteen.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellFourteen);

        sCalenderCellFifteen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellFifteen.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellFifteen);

        sCalenderCellSixteen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellSixteen.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellSixteen);

        sCalenderCellSeventeen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellSeventeen.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellSeventeen);

        sCalenderCellEighteen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellEighteen.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellEighteen);

        sCalenderCellNineteen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellNineteen.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellNineteen);

        sCalenderCellTwenty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellTwenty.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellTwenty);

        sCalenderCellTwentyOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellTwentyOne.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellTwentyOne);

        sCalenderCellTwentyTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellTwentyTwo.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellTwentyTwo);

        sCalenderCellTwentyThree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellTwentyThree.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellTwentyThree);

        sCalenderCellTwentyFour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellTwentyFour.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellTwentyFour);

        sCalenderCellTwentyFive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellTwentyFive.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellTwentyFive);

        sCalenderCellTwentySix.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellTwentySix.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellTwentySix);

        sCalenderCellTwentySeven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellTwentySeven.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellTwentySeven);

        sCalenderCellTwentyEight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellTwentyEight.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellTwentyEight);

        sCalenderCellTwentyNine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellTwentyNine.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellTwentyNine);

        sCalenderCellThirty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellThirty.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellThirty);

        sCalenderCellThirtyOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellThirtyOne.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellThirtyOne);

        sCalenderCellThirtyTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellThirtyTwo.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellThirtyTwo);

        sCalenderCellThirtyThree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellThirtyThree.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellThirtyThree);

        sCalenderCellThirtyFour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellThirtyFour.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellThirtyFour);

        sCalenderCellThirtyFive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellThirtyFive.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellThirtyFive);

        sCalenderCellThirtySix.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellThirtySix.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellThirtySix);

        sCalenderCellThirtySeven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellThirtySeven.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellThirtySeven);

        sCalenderCellThirtyEight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellThirtyEight.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellThirtyEight);

        sCalenderCellThirtyNine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellThirtyNine.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellThirtyNine);

        sCalenderCellFourty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellFourty.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellFourty);

        sCalenderCellFourtyOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellFourtyOne.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellFourtyOne);

        sCalenderCellFourtyTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sCalenderCellFourtyTwo.setLayout(new java.awt.GridLayout(0, 1));
        scCalenderPane.add(sCalenderCellFourtyTwo);

        scMainPane.add(scCalenderPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(scMainPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SCalender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SCalender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SCalender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SCalender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SCalender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApril;
    private javax.swing.JButton btnAugust;
    private javax.swing.JButton btnDecember;
    private javax.swing.JButton btnFebruary;
    private javax.swing.JButton btnJanuary;
    private javax.swing.JButton btnJuly;
    private javax.swing.JButton btnJune;
    private javax.swing.JButton btnMarch;
    private javax.swing.JButton btnMay;
    private javax.swing.JButton btnNovember;
    private javax.swing.JButton btnOctober;
    private javax.swing.JButton btnSeptember;
    private javax.swing.JComboBox cmbYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSelectYear;
    private javax.swing.JPanel sCalenderCellEight;
    private javax.swing.JPanel sCalenderCellEighteen;
    private javax.swing.JPanel sCalenderCellEleven;
    private javax.swing.JPanel sCalenderCellFifteen;
    private javax.swing.JPanel sCalenderCellFive;
    private javax.swing.JPanel sCalenderCellFour;
    private javax.swing.JPanel sCalenderCellFourteen;
    private javax.swing.JPanel sCalenderCellFourty;
    private javax.swing.JPanel sCalenderCellFourtyOne;
    private javax.swing.JPanel sCalenderCellFourtyTwo;
    private javax.swing.JPanel sCalenderCellNine;
    private javax.swing.JPanel sCalenderCellNineteen;
    private javax.swing.JPanel sCalenderCellOne;
    private javax.swing.JPanel sCalenderCellSeven;
    private javax.swing.JPanel sCalenderCellSeventeen;
    private javax.swing.JPanel sCalenderCellSix;
    private javax.swing.JPanel sCalenderCellSixteen;
    private javax.swing.JPanel sCalenderCellTen;
    private javax.swing.JPanel sCalenderCellThirteen;
    private javax.swing.JPanel sCalenderCellThirty;
    private javax.swing.JPanel sCalenderCellThirtyEight;
    private javax.swing.JPanel sCalenderCellThirtyFive;
    private javax.swing.JPanel sCalenderCellThirtyFour;
    private javax.swing.JPanel sCalenderCellThirtyNine;
    private javax.swing.JPanel sCalenderCellThirtyOne;
    private javax.swing.JPanel sCalenderCellThirtySeven;
    private javax.swing.JPanel sCalenderCellThirtySix;
    private javax.swing.JPanel sCalenderCellThirtyThree;
    private javax.swing.JPanel sCalenderCellThirtyTwo;
    private javax.swing.JPanel sCalenderCellThree;
    private javax.swing.JPanel sCalenderCellTwelve;
    private javax.swing.JPanel sCalenderCellTwenty;
    private javax.swing.JPanel sCalenderCellTwentyEight;
    private javax.swing.JPanel sCalenderCellTwentyFive;
    private javax.swing.JPanel sCalenderCellTwentyFour;
    private javax.swing.JPanel sCalenderCellTwentyNine;
    private javax.swing.JPanel sCalenderCellTwentyOne;
    private javax.swing.JPanel sCalenderCellTwentySeven;
    private javax.swing.JPanel sCalenderCellTwentySix;
    private javax.swing.JPanel sCalenderCellTwentyThree;
    private javax.swing.JPanel sCalenderCellTwentyTwo;
    private javax.swing.JPanel sCalenderCellTwo;
    private javax.swing.JPanel scCalenderPane;
    private javax.swing.JPanel scLeftPane;
    private javax.swing.JPanel scMainPane;
    // End of variables declaration//GEN-END:variables
}
